### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by derpoliuk** [realexpayments/rxp-ios#18]
`UIWebView` got deprecated in iOS 12.0, we are getting following message after submitting builds to App Store Connect:

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>**ITMS-90809: Deprecated API Usage** - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
>
>After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
>
>Best regards,
>
>The App Store Team

Do you have any plans on updating SDK to replace `UIWebView`?

**Comment by DannyGloudemans** [comment]
We're getting the same message from Apple when we publish the app into the App Store. It would be good to know when Global Payments will update the library, so that we know when we can update/upgrade the library in our mobile applications.

**Comment by DannyGloudemans** [comment]
Apple noticed they will start rejecting new apps in April 2020. Could you please let us know when this will be updated?

Thanks

**Comment by derpoliuk** [comment]
Fixed in https://github.com/globalpayments/rxp-ios/releases/tag/1.6.0. Closing this issue.
