### ISSUE TITLE
It is not compatible swift 3

### ISSUE THREAD

**Issue by cwinUser** [realexpayments/rxp-ios#5]
Can you please make update for swift 3 compatability.

**Comment by slogsdon** [comment]
Hi @cwinUser! Please watch #4 as Swift 3 compatibility is on the way. The last update I received was that the changes are going through internal review.

**Comment by TheSwiftyCoder** [comment]
Can we get an update on when this update is expected to drop?

**Comment by rxp-developers** [comment]
Hi @jay-cohen, @cwinUser, it's been reviewed and approved by our QA and Security teams so I've submitted the library for release today. It should be released before the end of next week. I will update here if that changes. Seán.

**Comment by rxp-developers** [comment]
Hi @jay-cohen, @cwinUser, this has been released today.

**Comment by cwinUser** [comment]
thank you .. (y)
